In [1]:
#Dependencies
import pandas as pd
from gensim import matutils, models
import scipy.sparse

In [2]:
#Bring in document-term matrix
dtm = pd.read_csv('state_tweets_dtm.csv')
dtm.head()

,state,able,academies,access,accessibility,accessible,accomplish,according,accounts,action,...,years,yearslong,yes,yesterdays,york,yorks,youre,zero,zoning,zoom
0,Alabama,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Alaska,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Arizona,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Arkansas,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,California,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
##Transpose data to a term-document matrix to fit w/gensim specs
tdm = dtm.transpose()
tdm.head()

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
state,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Florida,Georgia,Illinois,Indiana,...,Pennsylvania,Rhode Island,South Carolina,South Dakota,Texas,Utah,Virginia,Washington,Wisconsin,Wyoming
able,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
academies,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0
access,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
accessibility,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
##Transform data from df-->sparse matrix-->gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

TypeError: no supported conversion for types: (dtype('O'),)